#!/usr/bin/env bash

SOURCE_PATH="$HOME/dotfiles/oh-my-zsh-custom"
OH_MY_ZSH_CUSTOM_PATH="$HOME/.oh-my-zsh/custom"

# INSTALA Oh-my-zsh se não estiver instalado

if ! [ -d ~/.oh-my-zsh ]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi



# (RE)CRIA links dos arquivos oh-my-zsh custom

for file in $SOURCE_PATH/*.zsh
do
  FILENAME=$(basename -- $file)

  echo "file $FILENAME"

  rm -f $OH_MY_ZSH_CUSTOM_PATH/$FILENAME
  ln -s $file $OH_MY_ZSH_CUSTOM_PATH/$FILENAME
done