#!/usr/bin/env bash

# Este arquivo, quando alterado, precisa ser executado manualmente para
# escrever as configurações no arquivo .zshrc


# TEMA

novo_tema="steeef"

sed -i "s/ZSH_THEME=.*/ZSH_THEME=$novo_tema/" ~/.zshrc


# NVM
# TODO: Revisar

#source /usr/share/nvm/init-nvm.sh
#zstyle ':omz:plugins:nvm' lazy yes
#zstyle ':omz:plugins:nvm' autoload yes
#zstyle ':omz:plugins:nvm' silent-autoload yes


# PLUGINS

novos_plugins="z zsh-autosuggestions git"

sed -i "s/plugins=(.*)/plugins=($novos_plugins)/" ~/.zshrc