alias e='exit'
alias t='tmux'

# Docker

alias dk='docker'
alias dkc='docker-compose'
alias dkcs='docker-compose start'
alias dkpsa='docker ps -a'
alias dks='sudo systemctl start docker.service'

# DOTNET

alias dn='dotnet'
alias dnb='dotnet build'
alias dnbni='dotnet build --no-incremental'
alias dni='dotnet --info'
alias dnn='dotnet new'
alias dnre='dotnet restore'
alias dnt='dotnet test'

# Git

alias gadd='git add'
alias gbranch='git branch'
alias gbranchd='git branch -d'
alias gbranchvv='git branch -vv'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gctv='git commit -v'
alias gctav='git commit --amend -v'
alias gctsv='git commit -S -v'
alias gdif='git diff'
alias gdiff='git diff'
alias gfetch='git fetch'
alias gk='LANG=en_US gitk'
alias glog='git log'
alias glogo='git log --oneline'
alias gpull='git pull'
alias gpullr='git pull -r'
alias gpush='git push'
alias gpushf='git push -f'
alias gpushfwl='git push --force-with-lease'
alias gpushu='git push -u'
alias grb='git rebase'
alias gremotev='git remote -v'
alias gstash='git stash'
alias gstashm='git stash -m'
alias gstashd='git stash drop'
alias gstashl='git stash list'
alias gstashp='git stash pop'
alias gstashu='git stash -u'
alias gstashum='git stash -u -m'
alias gsw='git switch'
