#!/usr/bin/env bash

# INSTALA Oh-my-zsh se não estiver instalado

if ! [ -d ~/.oh-my-zsh ]; then
  # O Oh-my-zsh depende do zsh estar instalado

  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  echo "> OMZ installed!"

  # TODO: Fazer o script continua executando após instalar o Oh-my-zsh
fi

# INSTALA o plugin zsh-autosuggestions do Oh-my-zsh se não estiver instalado

if ! [ -d ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions ]; then
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

  echo "> OMZ auto sugestion plugin installed!"
fi


# (Re)Criar symlinks dos arquivos de configuracao

DOTFILES_DIR="$HOME/dotfiles"

echo "> Configs Files:"

for file in $(find $DOTFILES_DIR/configfiles/ -type f)
do
  FILENAME=$(basename -- $file)
  echo "- $FILENAME"

  echo "  SOURCE-FILE: $file"

  CONFIG_FILE=${file/dotfiles\/configfiles\//}
  echo "  CONFIG-FILE: $CONFIG_FILE"

  TARGET_DIR=${CONFIG_FILE/$FILENAME/}
  echo "  TARGET-DIR:  $TARGET_DIR"

  mkdir -p $TARGET_DIR
  ln -sf $file $CONFIG_FILE
done


# (Re)Cria symlinks dos arquivos oh-my-zsh custom

echo "> Custom OhMyZsh files:"

OH_MY_ZSH_CUSTOM_PATH="$HOME/.oh-my-zsh/custom"

for file in $DOTFILES_DIR/oh-my-zsh-custom/*.zsh
do
  FILENAME=$(basename -- $file)

  echo "- $FILENAME"
  echo "  SOURCE: $file"
  echo "  TARGET: $OH_MY_ZSH_CUSTOM_PATH/$FILENAME"

  ln -sf $file $OH_MY_ZSH_CUSTOM_PATH/$FILENAME
done
