#!/usr/bin/env bash

# Versão experimental (em desenvolvimento)
# Objetivo:
#  - Configuração automatizada do Manjaro
#  - Configuração automatizada do Git
#  - Instalação automatizada de pacotes Manjaro
#  - Remoção automatizada de pacotes Manjaro não utilizados


# CONFIGURAÇOES

## Git
echo "> Configurações Git"

### core.pager
git config --global core.pager ""
echo ">> core.pager configurado"

### core.editor
git config --global core.editor nvim
echo ">> core.editor configurado"

### user.email user.name
git config --global user.email "pedro.fernandesfilho@gmail.com"
git config --global user.name "Pedro Fernandes Filho"
echo ">> user.email e user.name configurado"



## Manjaro
echo "> Configuracões Manjaro"

### Níveis da bateria # /etc/UPower/UPower.conf

sudo cp /etc/UPower/UPower.conf /etc/UPower/UPower-BKP.conf

sudo sed -i 's/^PercentageLow=20/PercentageLow=6/' /etc/UPower/UPower.conf
sudo sed -i 's/^PercentageAction=2/PercentageAction=4/' /etc/UPower/UPower.conf
sudo sed -i 's/^CriticalPowerAction=HybridSleep/CriticalPowerAction=Hibernate/' /etc/UPower/UPower.conf

sudo systemctl restart upower.service

echo ">> Níveis de bateria configurados"


# PACOTES

## Instalação
echo "> Instalação de pacotes Manjaro"

sudo pacman -Sy alacritty tmux neovim neovide --noconfirm
sudo pacman -Sy discord steam --noconfirm

# Discord, Steam


## Desinstalar pacotes que vem na instalacao do Manjaro e não utlizo
echo "> Remoção de pacotes Manjaro"

## !!! Revisar quais pacots serão removidos de forma automatizada

  # lollypop totem snapshot fragments yelp deja-dup collision endeavour manjaro-hello
  # gnome-maps gnome-weather gnome-layout-swithcer gnome-tour gnome-clocks gnome-contacts

  # TODO: Verificar uma maneira de não dar erro se executar mais de uma vez
  #sudo pacman -Rsun deja-dup --noconfirm

## Versão testada

sudo pacman -Rsun thunderbird gnome-maps gnome-weather --noconfirm

### Remover órfãos

sudo pacman -Rsun $(pacman -Qdtq)
