#!/usr/bin/env bash

# Versão experimental (em desenvolvimento)
# Objetivo: Instalação automatizada de pacotes Manjaro

function installPackageIfNotInstalled() {
  local package=$1
  local command=${2:-$1}

  echo ""
  echo "> PACKAGE: '$package' ('$command')"

  if ! command -v $command &> /dev/null
  then
    echo "  ❗ Não instalado"
    echo "  🔨 Instalando..."
    sudo pacman -Sy $package --noconfirm
    # echo "  ✅ Feito!"
  else
    echo "  ☑️  Já instalado"
  fi
}

#installPackageIfNotInstalled "alacritty"
#installPackageIfNotInstalled "tmux"
#installPackageIfNotInstalled "neovim" "nvim"
#installPackageIfNotInstalled "neovide" # depende de nvim

sudo pacman -Sy alacritty tmux neovim neovide --noconfirm



# Desinstalar pacotes que vem na instalacao do manjaro

# thunderbird lollypop totem snapshot fragments yelp deja-dup collision endeavour manjaro-hello
# gnome-maps gnome-weather gnome-layout-swithcer gnome-tour gnome-clocks gnome-contacts

# Verificar uma maneira de não dar erro se executar mais de uma vez
#sudo pacman -Rsun deja-dup --noconfirm



# CONFIGURAÇOES

# Git
echo "> Configurações Git"
# - core.pager
git config --global core.pager ""
echo "  ✅ core.pager configurado!"
# - core.editor
git config --global core.editor neovide
echo "  ✅ core.editor configurado!"


# Manjaro
echo "> Configuracões Manjaro"

# Níveis da bateria # /etc/UPower/UPower.conf

sudo cp /etc/UPower/UPower.conf /etc/UPower/UPower-BKP.conf

sudo sed -i 's/^PercentageLow=20/PercentageLow=6/' /etc/UPower/UPower.conf
sudo sed -i 's/^PercentageAction=2/PercentageAction=4/' /etc/UPower/UPower.conf
sudo sed -i 's/^CriticalPowerAction=HybridSleep/CriticalPowerAction=Hibernate/' /etc/UPower/UPower.conf

sudo systemctl restart upower.service

echo "  ✅ Níveis de bateria configurados!"

